name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: Build, Package, Verify
        run: mvn --settings .github/workflows/settings.xml -B clean package verify install
      - name: Assembly
        run: mvn --settings .github/workflows/settings.xml -B --projects magpie-cli assembly:single
      - name: Upload zip
        uses:  actions/upload-artifact@v2
        with:
          name: magpie-cli
          path: magpie-cli/target/*.zip
      - name: Upload tar.gz
        uses:  actions/upload-artifact@v2
        with:
          name: magpie-cli
          path: magpie-cli/target/*.tar.gz
